# Generated by Django 3.0.2 on 2020-02-18 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
        migrations.RemoveField(
            model_name='course',
            name='t_id',
        ),
        migrations.RemoveField(
            model_name='enrollcourse',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='enrollcourse',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='enrollcourse',
            name='teachers_id',
        ),
        migrations.RemoveField(
            model_name='enrollcourse',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='news',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='viewsa',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='viewsa',
            name='tid',
        ),
        migrations.RemoveField(
            model_name='viewsa',
            name='uid',
        ),
        migrations.DeleteModel(
            name='course',
        ),
        migrations.DeleteModel(
            name='Enrollcourse',
        ),
        migrations.DeleteModel(
            name='ratings',
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.DeleteModel(
            name='teachers',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='viewsa',
        ),
    ]
