# Generated by Django 2.1.7 on 2020-02-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200218_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollcourse',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollcourse',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
    ]
