# Generated by Django 2.1.7 on 2020-02-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200224_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollcourse',
            name='tid',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
