# Generated by Django 3.0.2 on 2020-03-21 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_data_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='img',
        ),
    ]
