# Generated by Django 3.0.2 on 2020-03-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='location',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='news',
            name='newstitle',
            field=models.CharField(max_length=1000),
        ),
    ]
