# Generated by Django 3.0.2 on 2020-03-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200322_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('link', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=1000)),
                ('discription', models.CharField(max_length=1000)),
            ],
        ),
    ]
