# Generated by Django 3.0.2 on 2020-08-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_placeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
