# Generated by Django 3.0.2 on 2020-08-06 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_addtocart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='status',
        ),
    ]
