# Generated by Django 3.0.2 on 2020-08-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpost',
        ),
    ]
